### ISSUE TITLE
Migrate code to the terraform-aws-modules/terraform-aws-alb and publish in the registry

### ISSUE THREAD

**Issue by antonbabenko** [terraform-community-modules/tf_aws_alb#14]
Hi @brandoconnor ,

Could you please migrate this module to https://github.com/terraform-aws-modules/terraform-aws-alb ?

Send pull-requests, and we discuss the process as we go. This module is a good candidate to be very feature-rich and powerful.

Thanks,
Anton.

**Comment by brandonjbjelland** [comment]
Sure thing. Sending a PR now to get the ball rolling on that move.

**Comment by brandonjbjelland** [comment]
The PR is up here: https://github.com/terraform-aws-modules/terraform-aws-alb/pull/1. Closing the issue and migrating the other relevant issues.

Any chance I could be added to that org to help out and cut releases for that project? I've got a few other AWS modules in the waiting that I'd like to publish there if possible.

**Comment by antonbabenko** [comment]
Thanks for opening the PR. I will review it and provide my feedback on what should be changed/improved in order for it to be published as "verified" on the registry.

**Comment by brandonjbjelland** [comment]
Excellent and thanks for that. Always good to have another set of eyes on it.
